### ISSUE TITLE
Label required for Y axis

### ISSUE THREAD

**Issue by lhmarsden** [odileeds/covid-19#3]
I think this is a really nice tool, great work! I really like how I can easily compare two or more LAs.

I think it would be useful to include an axis label for your y axis. Currently, it is not clear whether you are presenting cumulative data or not, and therefore whether you are presenting new cases per day or total cases after n days.

If this data is cumulative, I am curious as to why in some cases the cumulative number of cases decreases through time (e.g. Leeds after 10 days, most easily seen on a log plot). 

Also, the hex plot skews the regional picture somewhat. For example, Birmingham appears much too far west. Have you considered plotting the data on a regular map but with zooms? I guess it might make it difficult to see smaller regions. Perhaps you could include an option to toggle between hex map and a normal map?

Kind regards,

Luke

**Comment by slowe** [comment]
@lhmarsden Thanks. I will add a y-axis label.

The data is cumulative. As the notes below it the graph say, the data come from @tomwhite's [data repo](https://github.com/tomwhite/covid-19-uk-data) and the early numbers are clearly not accurate; that is why some go down even though they shouldn't. 

With regards to the hex plot skewing the geography, yes, it won't be geographically exact because a hex plot is a trade-off. The purpose of hex maps are to make each unit equivalent and not hide the small ones. Is the problem that things don't feel to be in the right geographic place? [If you want to adjust the layout you can](https://odileeds.org/projects/hexmaps/builder?https://odileeds.github.io/hexmaps/maps/uk-local-authority-districts-2019.hexjson).

**Comment by slowe** [comment]
The y-axis label is now there.
